root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api" # Change from main.exe to main
bin = "tmp/main" # Change from tmp/main.exe to tmp/main
full_bin = ""
args = []
env = []
exclude_dir = ["tmp", "vendor", "scripts"]
exclude_file = []
exclude_ext = ["go"]
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = 0 # ms
log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
