services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

      - ./cmd/migrate/migrations:/migrations

volumes:
  db-data:
